title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Yash Parikh
github_username: illuminati1618
baseurl: "/YashParikhCSSE1"
#remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0

#addedbyme
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: pages-themes/primer@v0.6.0
#remote_theme: pages-themes/tactile@v0.2.0

plugins:
- jekyll-remote-theme
future: true
